name: Build And Test Plugin

on:
  pull_request_target:
  push:
    branches:
      - main

jobs:
  Get-CI-Image-Tag:
    uses: opensearch-project/opensearch-build/.github/workflows/get-ci-image-tag.yml@main
    with:
      product: opensearch

  build:
    runs-on: ubuntu-latest
    needs: Get-CI-Image-Tag
    container:
      # using the same image which is used by opensearch-build team to build the OpenSearch Distribution
      # this image tag is subject to change as more dependencies and updates will arrive over time
      image: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-version-linux }}
      # need to switch to root so that github actions can install runner binary on container without permission issues.
      options: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-start-options }}
    strategy:
      fail-fast: false
      matrix:
        java: [21, 25]
    name: Build & Format Check
    steps:
    - name: Run start commands
      run: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-start-command }}
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
    - name: Setup Container
      run: chown -R 1000:1000 `pwd`
    - name: Code Quality Verification Checks
      run: su `id -un 1000` -c "./gradlew precommit"
    - name: Build
      run: su `id -un 1000` -c "./gradlew assemble"
    - name: Upload build artifacts
      uses: actions/upload-artifact@v6
      with:
        name: build-artifacts-java-${{ matrix.java }}
        path:
          build/distributions/
        if-no-files-found: warn

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [21, 25]
    name: Test & Upload Code Coverage
    needs: build
    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
    - name: Run Unit Tests and Generate Code Coverage Report
      run: ./gradlew test
    - name: Run Integration Tests
      run: ./gradlew integTest
    - name: Upload Coverage Report to Codecov
      if: success() && env.CODECOV_TOKEN != ''
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./build/reports/jacoco/test/jacocoTestReport.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
    - name: Codecov upload skipped
      if: success() && env.CODECOV_TOKEN == ''
      run: echo "Codecov upload skipped - CODECOV_TOKEN not configured"
